export const LOGIN_REQUEST = 'LOGIN_REGUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_RESET = 'REGISTER_RESET';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const FORGOT_PASSWORD_RESET = 'FORGOT_PASSWORD_RESET';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const RESET_PASSWORD_RESET = 'RESET_PASSWORD_RESET';

export const USER_INFO_CHECK_REQUEST = 'USER_INFO_CHECK_REQUEST';
export const USER_INFO_CHECK_SUCCESS = 'USER_INFO_CHECK_SUCCESS';
export const USER_INFO_CHECK_FAIL = 'USER_INFO_CHECK_FAIL';
export const USER_INFO_CHECK_RESET = 'USER_INFO_CHECK_RESET';

export const REFRESH_INFO_REQUEST = 'REFRESH_INFO_REQUEST';
export const REFRESH_INFO_SUCCESS = 'REFRESH_INFO_SUCCESS';
export const REFRESH_INFO_FAIL = 'REFRESH_INFO_FAIL';
export const REFRESH_INFO_RESET = 'REFRESH_INFO_RESET';
