export const DIGITALCLASS_LIST_ALL_REQUEST = 'DIGITALCLASS_LIST_ALL_REQUEST';
export const DIGITALCLASS_LIST_ALL_SUCCESS = 'DIGITALCLASS_LIST_ALL_SUCCESS';
export const DIGITALCLASS_LIST_ALL_FAIL = 'DIGITALCLASS_LIST_ALL_FAIL';

export const DIGITALCLASS_DELETE_REQUEST = 'DIGITALCLASS_DELETE_REQUEST';
export const DIGITALCLASS_DELETE_SUCCESS = 'DIGITALCLASS_DELETE_SUCCESS';
export const DIGITALCLASS_DELETE_FAIL = 'DIGITALCLASS_DELETE_FAIL';
export const DIGITALCLASS_DELETE_RESET = 'DIGITALCLASS_DELETE_RESET';

export const DIGITALCLASS_LIST_REQUEST = 'DIGITALCLASS_LIST_REQUEST';
export const DIGITALCLASS_LIST_SUCCESS = 'DIGITALCLASS_LIST_SUCCESS';
export const DIGITALCLASS_LIST_FAIL = 'DIGITALCLASS_LIST_FAIL';

export const DIGITALCLASS_REQUEST = 'DIGITALCLASS_REQUEST';
export const DIGITALCLASS_SUCCESS = 'DIGITALCLASS_SUCCESS';
export const DIGITALCLASS_FAIL = 'DIGITALCLASS_FAIL';
export const DIGITALCLASS_RESET = 'DIGITALCLASS_RESET';

export const DIGITALCLASS_UPDATE_REQUEST = ' DIGITALCLASS_UPDATE_REQUEST';
export const DIGITALCLASS_UPDATE_SUCCESS = ' DIGITALCLASS_UPDATE_SUCCESS';
export const DIGITALCLASS_UPDATE_FAIL = ' DIGITALCLASS_UPDATE_FAIL';
export const DIGITALCLASS_UPDATE_RESET = ' DIGITALCLASS_UPDATE_RESET';

export const DIGITALCLASS_CREATE_REQUEST = 'DIGITALCLASS_CREATE_REQUEST';
export const DIGITALCLASS_CREATE_SUCCESS = 'DIGITALCLASS_CREATE_SUCCESS';
export const DIGITALCLASS_CREATE_FAIL = 'DIGITALCLASS_CREATE_FAIL';
export const DIGITALCLASS_CREATE_RESET = 'DIGITALCLASS_CREATE_RESET';

export const DIGITALCLASS_ENROLL_REQUEST = 'DIGITALCLASS_ENROLL_REQUEST';
export const DIGITALCLASS_ENROLL_SUCCESS = 'DIGITALCLASS_ENROLL_SUCCESS';
export const DIGITALCLASS_ENROLL_FAIL = 'DIGITALCLASS_ENROLL_FAIL';
export const DIGITALCLASS_ENROLL_RESET = 'DIGITALCLASS_ENROLL_RESET';
