export const DIGITALCLASS_LIST_REQUEST = 'DIGITALCLASS_LIST_REQUEST';
export const DIGITALCLASS_LIST_SUCCESS = 'DIGITALCLASS_LIST_SUCCESS';
export const DIGITALCLASS_LIST_FAIL = 'DIGITALCLASS_LIST_FAIL';
