export const DIGITALCLASS_LIST_REQUEST = 'DIGITALCLASS_LIST_REQUEST';
export const DIGITALCLASS_LIST_SUCCESS = 'DIGITALCLASS_LIST_SUCCESS';
export const DIGITALCLASS_LIST_FAIL = 'DIGITALCLASS_LIST_FAIL';

export const DIGITALCLASS_REQUEST = 'DIGITALCLASS_REQUEST';
export const DIGITALCLASS_SUCCESS = 'DIGITALCLASS_SUCCESS';
export const DIGITALCLASS_FAIL = 'DIGITALCLASS_FAIL';
export const DIGITALCLASS_RESET = 'DIGITALCLASS_RESET';

export const DIGITALCLASS_CREATE_REQUEST = 'DIGITALCLASS_CREATE_REQUEST';
export const DIGITALCLASS_CREATE_SUCCESS = 'DIGITALCLASS_CREATE_SUCCESS';
export const DIGITALCLASS_CREATE_FAIL = 'DIGITALCLASS_CREATE_FAIL';
export const DIGITALCLASS_CREATE_RESET = 'DIGITALCLASS_CREATE_RESET';
