export const GAME_CHECK_REQUEST = 'GAME_CHECK_REQUEST';
export const GAME_CHECK_SUCCESS = 'GAME_CHECK_SUCCESS';
export const GAME_CHECK_FAIL = 'GAME_CHECK_FAIL';
export const GAME_CHECK_RESET = 'GAME_CHECK_RESET';

export const START_GAME = 'START_GAME';
export const FETCHING_GAME = 'FETCHING_GAME';
export const PLAY_GAME = 'PLAY_GAME';
export const END_GAME = 'END_GAME';

export const FETCH_QUESTIONS_REQUEST = 'FETCH_QUESTIONS_REQUEST';
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_FAIL = 'FETCH_QUESTIONS_FAIL';
export const FETCH_QUESTIONS_RESET = 'FETCH_QUESTIONS_RESET';

export const SET_SCORE = 'SET_SCORE';
export const SET_INDEX = 'SET_INDEX';
export const SET_TRUE_ANS = 'SET_TRUE_ANS';
export const SET_FALSE_ANS = 'SET_FALSE_ANS';

export const SAVE_GAME_SCORE_REQUEST = 'SAVE_GAME_SCORE_REQUEST';
export const SAVE_GAME_SCORE_SUCCESS = 'SAVE_GAME_SCORE_SUCCESS';
export const SAVE_GAME_SCORE_FAIL = 'SAVE_GAME_SCORE_FAIL';

export const UPDATE_GAME_SCORE_REQUEST = 'UPDATE_GAME_SCORE_REQUEST';
export const UPDATE_GAME_SCORE_SUCCESS = 'UPDATE_GAME_SCORE_SUCCESS';
export const UPDATE_GAME_SCORE_FAIL = 'UPDATE_GAME_SCORE_FAIL';
