//<=======================Host==========================>
export const CONFIG_LIVE_GAME = 'CONFIG_LIVE_GAME';
export const WAITING_LIVE_GAME = 'WAITING_LIVE_GAME';
export const PLAY_LIVE_GAME = 'PLAY_LIVE_GAME';
export const END_LIVE_GAME = 'END_LIVE_GAME';

export const SET_HOST = 'SET_HOST';
export const SET_SETTINGS = 'SET_SETTINGS';

export const OPEN_ROOM_REQUEST = 'OPEN_ROOM_REQUEST';
export const OPEN_ROOM_SUCCESS = 'OPEN_ROOM_SUCCESS';
export const OPEN_ROOM_FAIL = 'OPEN_ROOM_FAIL';
export const OPEN_ROOM_RESET = 'OPEN_ROOM_RESET';

export const UPDATE_PLAYER_LOBBY = 'UPDATE_PLAYER_LOBBY';
export const START_GAME = 'START_GAME';
export const NEXT_QUESTION = 'NEXT_QUESTION';

export const FETCH_QUESTION_REQUEST = 'FETCH_QUESTION_REQUEST';
export const FETCH_QUESTION_SUCCESS = 'FETCH_QUESTION_SUCCESS';
export const FETCH_QUESTION_FAIL = 'FETCH_QUESTION_FAIL';
export const FETCH_QUESTION_RESET = 'FETCH_QUESTION_RESET';

export const UPDATE_PLAYERS_ANSWERED = 'UPDATE_PLAYERS_ANSWERED';
export const QUESTION_LIVE = 'QUESTION_LIVE';
export const LEADERDOARD = 'LEADERDOARD';
export const FILLER_SLIDE = 'FILLER_SLIDE';
export const CHART_BARS = 'CHART_BARS';

//<=======================Client==========================>

export const ENTRANCE_CLIENT_LIVE_GAME = 'ENTRANCE_CLIENT_LIVE_GAME';
export const WAITING_CLIENT_LIVE_GAME = 'WAITING_CLIENT_LIVE_GAME';
export const PLAY_CLIENT_LIVE_GAME = 'PLAY_CLIENT_LIVE_GAME';
export const END_CLIENT_LIVE_GAME = 'END_CLIENT_LIVE_GAME';

export const SET_PLAYER = 'SET_PLAYER';

export const ENTRY_GAME_REQUEST = 'ENTRY_GAME_REQUEST';
export const ENTRY_GAME_SUCCESS = 'ENTRY_GAME_SUCCESS';
export const ENTRY_GAME_FAIL = 'ENTRY_GAME_FAIL';

export const PLAYER_JOIN_REQUEST = 'PLAYER_JOIN_REQUEST';
export const PLAYER_JOIN_SUCCESS = 'PLAYER_JOIN_SUCCESS';
export const PLAYER_JOIN_FAIL = 'PLAYER_JOIN_FAIL';
export const PLAYER_JOIN_RESET = 'PLAYER_JOIN_RESET';

export const GET_STARTED = 'GET_STARTED';

export const PLAYER_JOIN_GAME_REQUEST = 'PLAYER_JOIN_GAME_REQUEST';
export const PLAYER_JOIN_GAME_SUCCESS = 'PLAYER_JOIN_GAME_SUCCESS';
export const PLAYER_JOIN_GAME_FAIL = 'PLAYER_JOIN_GAME_FAIL';
export const PLAYER_JOIN_GAME_RESET = 'PLAYER_JOIN_GAME_RESET';

export const PLAYER_ANSWER_QUESTION = 'PLAYER_ANSWER_QUESTION';
export const CORRECT_ANSWER = 'CORRECT_ANSWER';
export const FEEDBACK_ANSWER = 'FEEDBACK_ANSWER';
export const TIME_UP = 'TIME_UP';
export const PLAYER_DATA = 'PLAYER_DATA';
export const PLAYER_DISABLE = 'PLAYER_DISABLE';
