export const REPORT_LIST_REQUEST = 'REPORT_LIST_REQUEST';
export const REPORT_LIST_SUCCESS = 'REPORT_LIST_SUCCESS';
export const REPORT_LIST_FAIL = 'REPORT_LIST_FAIL';

export const REPORT_DELETE_REQUEST = 'REPORT_DELETE_REQUEST';
export const REPORT_DELETE_SUCCESS = 'REPORT_DELETE_SUCCESS';
export const REPORT_DELETE_FAIL = 'REPORT_DELETE_FAIL';
export const REPORT_DETELE_RESET = 'REPORT_DELETE_RESET';

export const REPORT_CREATE_REQUEST = 'REPORT_CREATE_REQUEST';
export const REPORT_CREATE_SUCCESS = 'REPORT_CREATE_SUCCESS';
export const REPORT_CREATE_FAIL = 'REPORT_CREATE_FAIL';
export const REPORT_CREATE_RESET = 'REPORT_CREATE_RESET';

export const REPORT_CHECK_REQUEST = 'REPORT_CHECK_REQUEST';
export const REPORT_CHECK_SUCCESS = 'REPORT_CHECK_SUCCESS';
export const REPORT_CHECK_FAIL = 'REPORT_CHECK_FAIL';
