export const STATISTICS_DASHBOARD_REQUEST = 'STATISTICS_DASHBOARD_REQUEST';
export const STATISTICS_DASHBOARD_SUCCESS = 'STATISTICS_DASHBOARD_SUCCESS';
export const STATISTICS_DASHBOARD_FAIL = 'STATISTICS_DASHBOARD_FAIL';

export const STATISTICS_REQUEST = 'STATISTICS_REQUEST';
export const STATISTICS_SUCCESS = 'STATISTICS_SUCCESS';
export const STATISTICS_FAIL = 'STATISTICS_FAIL';
export const STATISTICS_RESET = 'STATISTICS_RESET';

export const STATISTICS_DELETE_REQUEST = 'STATISTICS_DELETE_REQUEST';
export const STATISTICS_DELETE_SUCCESS = 'STATISTICS_DELETE_SUCCESS';
export const STATISTICS_DELETE_FAIL = 'STATISTICS_DELETE_FAIL';
export const STATISTICS_DELETE_RESET = 'STATISTICS_DELETE_RESET';

export const SCORE_REQUEST = 'SCORE_REQUEST';
export const SCORE_SUCCESS = 'SCORE_SUCCESS';
export const SCORE_FAIL = 'SCORE_FAIL';

export const USERS_INCLASS_REQUEST = 'USERS_INCLASS_REQUEST';
export const USERS_INCLASS_SUCCESS = 'USERS_INCLASS_SUCCESS';
export const USERS_INCLASS_FAIL = 'USERS_INCLASS_FAIL';

export const USERS_INCLASS_DELETE_REQUEST = 'USERS_INCLASS_DELETE_REQUEST';
export const USERS_INCLASS_DELETE_SUCCESS = 'USERS_INCLASS_DELETE_SUCCESS';
export const USERS_INCLASS_DELETE_FAIL = 'USERS_INCLASS_DELETE_FAIL';
export const USERS_INCLASS_DELETE_RESET = 'USERS_INCLASS_DELETE_RESET';
