export const STATISTICS_REQUEST = 'STATISTICS_REQUEST';
export const STATISTICS_SUCCESS = 'STATISTICS_SUCCESS';
export const STATISTICS_FAIL = 'STATISTICS_FAIL';

export const SCORE_REQUEST = 'SCORE_REQUEST';
export const SCORE_SUCCESS = 'SCORE_SUCCESS';
export const SCORE_FAIL = 'SCORE_FAIL';

export const USERS_INCLASS_REQUEST = 'USERS_INCLASS_REQUEST';
export const USERS_INCLASS_SUCCESS = 'USERS_INCLASS_SUCCESS';
export const USERS_INCLASS_FAIL = 'USERS_INCLASS_FAIL';
