export const SUGGEST_LIST_REQUEST = 'SUGGEST_LIST_REQUEST';
export const SUGGEST_LIST_SUCCESS = 'SUGGEST_LIST_SUCCESS';
export const SUGGEST_LIST_FAIL = 'SUGGEST_LIST_FAIL';

export const SUGGEST_ADD_REQUEST = 'SUGGEST_ADD_REQUEST';
export const SUGGEST_ADD_SUCCESS = 'SUGGEST_ADD_SUCCESS';
export const SUGGEST_ADD_FAIL = 'SUGGEST_ADD_FAIL';
export const SUGGEST_ADD_RESET = 'SUGGEST_ADD_RESET';

export const SUGGEST_DCLASS_AVAL_REQUEST = 'SUGGEST_DCLASS_AVAL_REQUEST';
export const SUGGEST_DCLASS_AVAL_SUCCESS = 'SUGGEST_DCLASS_AVAL_SUCCESS';
export const SUGGEST_DCLASS_AVAL_FAIL = 'SUGGEST_DCLASS_AVAL_FAIL';
export const SUGGEST_DCLASS_AVAL_RESET = 'SUGGEST_DCLASS_AVAL_RESET';
