export const LIVE_QUIZ_LIST_REQUEST = 'LIVE_QUIZ_LIST_REQUEST';
export const LIVE_QUIZ_LIST_SUCCESS = 'LIVE_QUIZ_LIST_SUCCESS';
export const LIVE_QUIZ_LIST_FAIL = 'LIVE_QUIZ_LIST_FAIL';
export const LIVE_QUIZ_LIST_RESET = 'LIVE_QUIZ_LIST_RESET';

export const LIVE_QUIZ_STATISTICS_REQUEST = 'LIVE_QUIZ_STATISTICS_REQUEST';
export const LIVE_QUIZ_STATISTICS_SUCCESS = 'LIVE_QUIZ_STATISTICS_SUCCESS';
export const LIVE_QUIZ_STATISTICS_FAIL = 'LIVE_QUIZ_STATISTICS_FAIL';
export const LIVE_QUIZ_STATISTICS_RESET = 'LIVE_QUIZ_STATISTICS_RESET';

export const LIVE_QUIZ_DELETE_REQUEST = 'LIVE_QUIZ_DELETE_REQUEST';
export const LIVE_QUIZ_DELETE_SUCCESS = 'LIVE_QUIZ_DELETE_SUCCESS';
export const LIVE_QUIZ_DELETE_FAIL = 'LIVE_QUIZ_DELETE_FAIL';
export const LIVE_QUIZ_DETELE_RESET = 'LIVE_QUIZ_DELETE_RESET';
